const categoryLabels: Record<string, string> = {
  "accordion": "القائمة القابلة للطي",
  "alert": "التنبيه",
  "alert dialog": "نافذة التنبيه",
  "autocomplete": "الإكمال التلقائي",
  "avatar": "الصورة الشخصية",
  "badge": "الشارة",
  "breadcrumb": "مسار التنقل",
  "button": "الزر",
  "calendar": "التقويم",
  "card": "البطاقة",
  "checkbox": "مربع الاختيار",
  "checkbox group": "مجموعة مربعات الاختيار",
  "collapsible": "المحتوى القابل للطي",
  "combobox": "مربع الاختيار والبحث",
  "command": "قائمة الأوامر",
  "context menu": "قائمة السياق",
  "date picker": "منتقي التاريخ",
  "dialog": "النافذة الحوارية",
  "drawer": "اللوحة المنزلقة",
  "empty": "الحالة الفارغة",
  "empty state": "الحالة الفارغة",
  "field": "حقل النموذج",
  "fieldset": "مجموعة الحقول",
  "form": "النموذج",
  "frame": "الإطار",
  "group": "المجموعة",
  "input": "حقل الإدخال",
  "input group": "مجموعة الإدخال",
  "kbd": "مفتاح لوحة المفاتيح",
  "label": "التسمية",
  "menu": "القائمة",
  "meter": "مقياس القيمة",
  "navigation": "التنقل",
  "number field": "حقل الأرقام",
  "otp field": "رمز التحقق",
  "pagination": "ترقيم الصفحات",
  "popover": "النافذة المنبثقة",
  "preview card": "بطاقة المعاينة",
  "progress": "مؤشر التقدم",
  "radio group": "مجموعة الاختيار الأحادي",
  "scroll area": "منطقة التمرير",
  "select": "الاختيار",
  "segmented control": "الاختيار المقسّم",
  "separator": "الفاصل",
  "sheet": "اللوحة الجانبية",
  "skeleton": "هيكل التحميل",
  "slider": "شريط التمرير",
  "spinner": "مؤشر التحميل",
  "switch": "مفتاح التبديل",
  "table": "الجدول",
  "tabs": "التبويبات",
  "textarea": "مساحة النص",
  "toast": "الإشعار العابر",
  "toggle": "زر التبديل",
  "toggle group": "مجموعة أزرار التبديل",
  "toolbar": "شريط الأدوات",
  "tooltip": "التلميح",
  "async": "غير متزامن",
  "copy": "نسخ",
  "disabled": "معطّل",
  "error": "خطأ",
  "file": "ملف",
  "filter": "تصفية",
  "info": "معلومة",
  "loading": "تحميل",
  "multiselect": "اختيار متعدد",
  "password": "كلمة المرور",
  "search": "بحث",
  "sort": "ترتيب",
  "success": "نجاح",
  "tag": "وسم",
  "tanstack": "جدول البيانات",
  "text editor": "محرر النصوص",
  "time": "وقت",
  "timezone": "منطقة زمنية",
  "upload": "رفع",
  "validation": "تحقق",
  "warning": "تحذير",
  "zod": "التحقق من البيانات",
  "dropdown": "قائمة منسدلة",
  "banner": "تنبيه علوي",
  "crop": "اقتصاص",
  "notification": "إشعار",
  "otp": "رمز تحقق",
  "radio": "اختيار أحادي",
  "sonner": "إشعارات",
  "stepper": "مراحل",
  "timeline": "خط زمني",
  "authentication": "تسجيل الدخول",
  "avatar group": "مجموعة صور شخصية",
  "back": "رجوع",
  "chart": "مخطط",
  "checkout": "إتمام الشراء",
  "chip": "وسم",
  "color": "لون",
  "controls": "عناصر التحكم",
  "cookies": "ملفات الارتباط",
  "countdown": "عدّ تنازلي",
  "counter": "عدّاد",
  "credit card": "بطاقة ائتمان",
  "darkmode": "المظهر الداكن",
  "date": "تاريخ",
  "delete": "حذف",
  "download": "تنزيل",
  "feedback": "ملاحظات",
  "formatting": "تنسيق",
  "icon": "أيقونة",
  "image": "صورة",
  "link": "رابط",
  "list": "قائمة",
  "login": "تسجيل الدخول",
  "message": "رسالة",
  "navigation menu": "قائمة التنقل",
  "number": "رقم",
  "payment": "دفع",
  "phone": "هاتف",
  "pricing": "الأسعار",
  "progress bar": "شريط التقدم",
  "rating": "تقييم",
  "rich text": "نص منسق",
  "search input": "حقل البحث",
  "settings": "إعدادات",
  "text": "نص",
  "tree": "شجرة",
  "video": "فيديو",
  "wizard": "خطوات",
  "react aria": "مكونات الوصول",
  "react day picker": "منتقي التاريخ",
  "event calendar": "تقويم الأحداث",
  "input otp": "رمز التحقق",
  "file upload": "رفع الملفات",
  "resizable": "تغيير الحجم",
  "layout": "التخطيط",
  "scroll": "تمرير",
  "form validation": "التحقق من النموذج"
};

export function categoryLabel(value: string): string {
  return categoryLabels[value.toLowerCase()] || value;
}
